rp: add missing `Dict` import from `typing`
Problem: `import psi.j` fails with:
```
❯ python3 -c 'import psi.j'                                                                                                                                                                                19:51:33 ()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 74, in <module>
    _find_plugins(path, type, 0)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 63, in _find_plugins
    _find_plugins(path + os.path.sep + mod.name, type, ix + 1)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 63, in _find_plugins
    _find_plugins(path + os.path.sep + mod.name, type, ix + 1)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 63, in _find_plugins
    _find_plugins(path + os.path.sep + mod.name, type, ix + 1)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 59, in _find_plugins
    _load_plugins(path, type)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 47, in _load_plugins
    im = importlib.import_module('psi.j.{}.{}'.format(type.name, mod.name))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/executors/__init__.py", line 4, in <module>
    from .rp import RPJobExecutor
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/executors/rp.py", line 17, in <module>
    class RPJobExecutor(JobExecutor):
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/executors/rp.py", line 124, in RPJobExecutor
    def _job_2_descr(self, job: Job) -> Dict[str, Any]:
NameError: name 'Dict' is not defined
```

Solution: add `Dict` to the `from typing import` line